[package]
name = "poufs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3"
aes = "0.8"
cbc = "0.1.2"