[package]
name = "drivebench"
version = "0.1.0"
authors = ["Zyf <zyfarok@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
threadpool = "1.8"
num_cpus = "1.13"